version: '2'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
    volumes_from:        
      - app
    restart: always
    environment:
      DOMAINS: 'bazaar.community -> http://35.237.226.230:46658'
      STAGE: 'production'
      WEBSOCKET: 'true'
      # FORCE_RENEW: 'true'
  app:
    build: .
